lib/app_web/router.ex
defmodule AppWeb.Router do
  use AppWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug App.AuthPipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AppWeb do
    pipe_through :browser
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/", AppWeb do
    pipe_through [:browser, :browser_auth]
    get "/", PageController, :index

    resources "/products", ProductController
    post "/products/:product_id/edit", ProductController, :edit
    post "/products/:product_id", ProductController, :update
  end

  scope "/", AppWeb do
    pipe_through [:browser]
    resources "/users", UserController, only: [:new, :create, :edit]
  end

  scope "/", AppWeb do
    pipe_through [:browser, :browser_auth, :ensure_auth]

    resources "/users", UserController
    resources "/ratings", RatingController

    # post "/search", AppController, :search
    # get "/allocations/new/:parking_lot_id", AllocationController, :custom_new
    # resources "/allocations", AllocationController, only: [:index, :create, :show, :edit, :update]
    # post "/allocations/new/:allocation_id", AllocationController, :payment
    # resources "/invoices", InvoiceController, only: [:index, :show]
  end


  # Other scopes may use custom stacks.
  # scope "/api", AppWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AppWeb.Telemetry
    end
  end
end

lib/app_web/views/layout_view.ex
defmodule AppWeb.LayoutView do
  use AppWeb, :view
end

lib/app_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>App · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <ol class="breadcrumb pull-right">
            <%= if App.Authentication.load_current_user(@conn) do %>
                <li>Current time: <%= NaiveDateTime.truncate(NaiveDateTime.local_now(), :second) %></li>
                <li>Hello <%= App.Authentication.load_current_user(@conn).name %></li>
                <li><%= link "Account", to: Routes.user_path(@conn, :show, App.Authentication.load_current_user(@conn)), class: "btn btn-default btn-xs", id: "account" %></li>
                <li><%= link "Log out", to: Routes.session_path(@conn, :delete, App.Authentication.load_current_user(@conn)), method: "delete", id: "log_out" %></li>
                <li><%= link("Main menu", to: Routes.page_path(@conn, :index), method: "get", class: "button", id: "main-menu-button") %></li>
            <% else %>
                <li><%= link "Log in", to: Routes.session_path(@conn, :new) %></li>
                <li><%= link "Register", to: Routes.user_path(@conn, :new) %></li>
            <% end %>
          </ol>
        <span class="logo"></span>

        </nav>
        <a href="https://phoenixframework.org/" class="phx-logo">
          <img src="<%= Routes.static_path(@conn, "/images/phoenix.png") %>" alt="Phoenix Framework Logo"/>
        </a>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>